### PR TITLE
Fix dropping block into toggle drops it into correct place but not part of toggle

### LINKED ISSUE #203: dropping block into toggle drops it into correct place but not part of toggle
### Precheck

- [ ] Do a quick search and make sure the bug has not been reported yet.
- [ ] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [ ] Finally, be nice and have fun!.

### Description

dropping block into toggle drops it into correct place but not part of toggle - the indent is different than toggle items plus closing toggle does not hide item

### Environment

* Editor.js version: latest
* Device, Browser, OS: windows local browser test

plugins:
<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/editorjs-drag-drop"></script>
    <script src="https://cdn.jsdelivr.net/npm/editorjs-undo"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/image@2.3.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/header@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/simple-image@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/embed@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/delimiter@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/editorjs-toggle-block"></script>

### Current behavior

to reproduce:
add a toggle block, click and add several text items
using shift tab, add another text item below the block
drag the outside block into the toggle
observe indent
try to close toggle

dragging items out works ok

### Expected behavior

I expect when dragging an item into the toggle block that it will match the indent and close with the toggle

### PR DESCRIPTION
**Pull request by Odraxs**
Closes #203 

## Description

This pull request solves the drag-and-drop feature to move items inside and outside the toggle element. Also, it solves the tab shortcut to add items to toggle block.

## Evidence

Before: 

https://github.com/kommitters/editorjs-toggle-block/assets/64106728/aee4942b-9948-4aa6-b32e-8e6b0190b1fb

**Note**: The error in the console appears when the tab key is pressed to include the item in the toggle. 

After:

https://github.com/kommitters/editorjs-toggle-block/assets/64106728/9a28e3b5-3202-4fdd-ac70-7ed789f7fbc5

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -836,15 +836,13 @@ export default class ToggleBlock {
...
-        const blockCover = blockContainer.parentElement;
-        const block = blockCover.parentElement;
+        const currentBlock = this.getCurrentBlockIndex();
+        const { holder: currentBlockContainer } = this.getBlockByIndex(currentBlock);
 
         if (e.code === 'Space') {
           this.createToggleWithShortcut(blockContainer);
-        } else if (currentBlock > 0 && !(this.isPartOfAToggle(blockContainer) || this.isPartOfAToggle(block)) && e.code === 'Tab') {
-          this.nestBlock(blockContainer);
+        } else if (currentBlock > 0 && !(this.isPartOfAToggle(currentBlockContainer)) && e.code === 'Tab') {
```
Comment (miguelnietoa) [inline src/index.js:844]: Please remove the parenthesis after `!`

File: src/index.js [hunk 2]
```diff
@@ -965,6 +956,9 @@ export default class ToggleBlock {
                     }
                   }
                 }
+              } else if (this.nameDragged) {
+                // Add the drooped item as an element of the toggle
```
Comment (miguelnietoa) [inline src/index.js:960]: Fix typo "drooped"

**Review by miguelnietoa — CHANGES_REQUESTED** [review]
Good fix! I only add two minor comments

**Review by miguelnietoa — APPROVED** [review]
